module.exports = {
  buffer: require('./buffer'),
  rms: require('./rms'),
  energy: require('./energy'),
  complexSpectrum: require('./complexSpectrum'),
  spectralSlope: require('./spectralSlope'),
  spectralCentroid: require('./spectralCentroid'),
  spectralRolloff: require('./spectralRolloff'),
  spectralFlatness: require('./spectralFlatness'),
  spectralSpread: require('./spectralSpread'),
  spectralSkewness: require('./spectralSkewness'),
  spectralKurtosis: require('./spectralKurtosis'),
  amplitudeSpectrum: require('./amplitudeSpectrum'),
  zcr: require('./zcr'),
  powerSpectrum: require('./powerSpectrum'),
  loudnessObject: require('./loudness'),
  perceptualSpread: require('./perceptualSpread'),
  perceptualSharpness: require('./perceptualSharpness'),
  mfcc: require('./mfcc')
};